### ISSUE TITLE
How can i use the model in sd-webui-controlnet

### ISSUE THREAD

**Issue by Hetaneko** [jinxixiang/color_controlnet#2]
Thank you for these models! I was just wondering if it is possible to use these models in [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet)
I tried to use it but i get `state_dict` errors

**Comment by jinxixiang** [comment]
Thank you for your interest. Unfortunately, the current version is not compatible with sd-webui-controlnet. We have designed it as a standalone extension to provide users with editable tools.

**Comment by jinxixiang** [comment]
We are considering releasing an extension in sd-web-UI. Please stay tuned. Thanks.
