### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionImg2ImgControlNetPalettePipeline' from 'diffusers' 

### ISSUE THREAD

**Issue by ArefMYTB** [jinxixiang/color_controlnet#6]
I tried to run it on colab but I got below error:

Traceback (most recent call last):
  File "/content/color_controlnet/infer_palette_img2img.py", line 5, in <module>
    from diffusers import ControlNetModel, LineartDetector, StableDiffusionImg2ImgControlNetPalettePipeline
ImportError: cannot import name 'StableDiffusionImg2ImgControlNetPalettePipeline' from 'diffusers' (/content/color_controlnet/diffusers/__init__.py)

**Comment by jinxixiang** [comment]
this error indicates version conflict with the local diffusers if you have already installed diffusers from pip.
